# Generated by Django 5.0.3 on 2024-05-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_akshada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='')),
            ],
        ),
    ]
