# Generated by Django 5.0.3 on 2024-05-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_fil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mohan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
